schema_version: 1

context:
  name: prek
  version: "0.2.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/j178/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1af34eb6bf3beb19b73b334f63f77c9225b1c6d57a5bdb53752ad06135843396

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - prek --help

about:
  homepage: https://prek.j178.dev
  summary: Better `pre-commit`, re-engineered in Rust
  repository: https://github.com/j178/prek
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
    - licenses/LICENSE.pre-commit.txt
    - licenses/LICENSE.identify.txt
    - crates/prek-pty/LICENSE

extra:
  recipe-maintainers:
    - weiji14
    - ocefpaf
